version: "3.9"

networks:
  brilhador:
    driver: bridge
services:
  authentication-spring-boot:
    container_name: authentication-spring-boot
    image: openjdk:17.0.2-slim-buster
    volumes:
      - ./authentication:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  postgres-brilhador:
    container_name: postgres-brilhador
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "brilhador"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - brilhador
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_CONFIG_FILE: ./rabbitmq.conf
    ports:
      - "5673:5673"
      - "15672:15672"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - brilhador
  api-gateway:
    container_name: brilhador-api-gateway
    image: openjdk:17.0.2-slim-buster
    working_dir: /app
    ports:
      - "4000:8080"
    volumes:
      - ./api-gateway:/app
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador